### ISSUE TITLE
[EPIC] Permettre aux entreprises de choisir clairement si elles sont exposées uniquement sur IF, uniquement sur les portails "jeunes" et EN ou sur les 2 types d'environnement

### ISSUE THREAD

**Issue by nathalie-reyre** [gip-inclusion/immersion-facile#1036]
Partage de notre moteur de recherche et de notre base à 1J/1S pour les stages de 3e/2nde, aux CCI pour le mini stage et en réflexion à l'EN pour les lycées professionnels. 
Il faut en informer les entreprises car les conditions d'accueil de collégiens/lycéens peuvent être différentes et les motivations pour les accueillir également.  Les entreprises doivent pouvoir choisir facilement où elles souhaitent être exposées

--
Grooming du 16 janvier : 

### :thinking: Contexte et problématique

l'annuaire et le moteur de recherche vont être utilisé par 1J/1solution et par les CCI/CMA pour permettre à des publics scolaire ou jeune étudiant de faire des stages de découverte (stage 3" et 2nde et mini stage. Par ailleurs, le ministère de l'Education nationale et le ministère de l'économie ont recensé 200 000 entreprises prêtes à accueillir des jeunes scolarisés. Ces entreprises vont être encouragées à se référencer comme entreprise accueillante via le formulaire hébergé sur 1J/1S qui alimente la base des entreprises accueillantes. 

Il faut permettre à ces entreprises de choisir d'être contactées par le public de leur choix  : 
- soit tout public (IF, 1J/1S CCI/CMA),
- soit uniquement public  scolaire (1J/1 solution et CCI/CMA),
- soit uniquement pour des PMSMP (IF).

### :tada: Proposition de solution

 
- [ ] back - création du champ/table ad hoc dans la base, 
- [ ] back - catégorisation présente dans l'API pour permettre d'appeler le bon type d'entreprises en fonction de l'objectif du site utilisateur de l'AP.
- [ ] front - ajout des choix possibles dans le formulaire de référencement entreprise, 
- [ ] front - ajouter le type de stage dans la demande de mise en relation - form + emails (et expliquer la différence entre les types de stages aux candidats et entreprises).
- [ ] front - ajouter le critère de recherche "type de stage".
- [ ] email de màj entreprise : ajouter ce critère + mailing dédie.
- [ ] prévenir 1J1S qu'ils peuvent intégrer une iframe de notre formulaire sans header/footer -> https://www.1jeune1solution.gouv.fr/immersions/referencer-mon-entreprise

L'idéal serait d'avoir en prod ces solutions fin janv/début février afin d'être en phase avec l'exposition sur 1J/1S.
On peut faire un rattrapage des entreprises déjà enregistrées via un mailing pour les informer et leur préciser que leur choix peut être précisé en mettant à jour leur fiche. En l'absence de mise à jour, les entreprises sont exposées partout.

**Comment by 3lodi3** [comment]
Suite à la discussion de ce matin avec @nathalie-reyre voici un petit schéma du parcours attendu 
![Parcours annuaire d'entreprises 1J1S - CCI_CMA - IF - Flow](https://github.com/gip-inclusion/immersion-facile/assets/76998405/56d4b48a-917b-44a1-8c37-c84ade113c66)

Pour le front on ne changerait pour l'instant que le parcours de référencement/modification entreprises qui serait repris tel quel en iframe chez nos partenaires : https://www.figma.com/proto/6msAgGCn4id2P3OjI4NRxP/Site---UX-design-1er-semestre-2024?page-id=6%3A303&type=design&node-id=6-1171&viewport=901%2C343%2C0.16&t=67eiWBeuxvoHMcX4-1&scaling=min-zoom&mode=design

J'ai juste un petit flou encore sur où apparaîtront les entreprises qui ont choisi "publics scolaires" : sur 1J1S c'est sûr mais qu'est-ce que ça implique côté CCI/CMA ?

@gip-inclusion/immersion-facilitee-dev

**Comment by nathalie-reyre** [comment]
pour les CCI/CMA , c'est pas encore défini. On va leur proposer mais pas encore programmé chez eux. L'immédiat, c'est 1J/1solution et 1 module spécifique de Diagoriente. 
Commentaire/maquette : pas trop pour le terme "bénéficiaires en reconversion" --> plus "bénéficiaires en parcours professionnel" ou "bénéficiaires en projet professionnel" pour tenir compte de toutes les trajectoires

**Comment by nathalie-reyre** [comment]
Pour info, j'ai eu un échange tel avec une personne qui accompagne le Medef sur le sujet stage de 2nde --> très rassuré à l'idée que tout converge vers nous. l'avait de lui même suggéré aux instances dirigeantes du Medef

**Comment by 3lodi3** [comment]
Parler plutôt de public visé ?
Parler de personnes en parcours professionnel. / publics non scolaires ?

Public sco : 1J1S, ( en cours : sites des CCI, module diagoriente (entrée orientation dédiée aux collèges et lycées)).

**Comment by 3lodi3** [comment]
Revoir l'UX/UI avec retours @3lodi3
