### ISSUE TITLE
[EPIC] ETQ que prescripteur je peux gérer mon référencement, demander une modification de mes informations au même titre qu'un référencement ENT

### ISSUE THREAD

**Issue by NastassiaRodriguez** [gip-inclusion/immersion-facile#1150]
Le problème : Nous avons de plus en plus de demande de modifications sur les référencements des prescripteurs, et également des doublons à gérer. 

Dépend de la refonte des droits

Droit "responsable d'agence" :
- [ ] peut modifier la fiche agence, 
- [ ] ajouter/supprimer des conseillers et valideurs
- [ ] pas de droits pour piloter des conventions

Il faut gérer que des responsables d'agence auront aussi des droits en tant que conseiller ou valideur.

- [ ] Ajout d'un onglet gestion agence comme pour les entreprises
- [ ] Définir en backoffice quel compte IC a les droits admin pour les agences existantes
- [ ] Envoyer un email à cette personne pour lui expliquer ce qu'elle peut faire en admin

Que fait-on pour les comptes avec des adresses mail génériques ?
-> On préconise plutôt une adresse perso pour pouvoir tracker qui fait les modifs, après c'est leur gestion interne.

Etape 1 :
@nathalie-reyre : demander les listes
- Pour FT : Obtenir la liste des emails + code azure
- Pour milo : liste des directeurs

Etape 2 :
On développe cet onglet et on donne les droits au coup par coup quand les prescripteurs demandent à pouvoir éditer leur structure.

Page édition d'agence : Avant de pouvoir supprimer le dernier admin, on demande à l'utilisateur d'en nommer un autre.

**Comment by 3lodi3** [comment]
https://docs.google.com/spreadsheets/d/1o9SU-U_70a8bsmgsI_XfSgsafoVXd0ZB/edit?usp=sharing&ouid=114304560171371596624&rtpof=true&sd=true

**Comment by chaibax** [comment]
Hello @nathalie-reyre , en quoi c'est lié a une action FAST vu au kickoff, ou ajouté pendant notre rituel fast sur le tableau FAST trello : https://trello.com/b/18KYeyer/kickoff-fast-if ?

**Comment by NastassiaRodriguez** [comment]
@3lodi3 on a une demande de pouvoir en admin sur son référencement gérer ses structures sur plusieurs sites, exemple MILO : 1 agence mère qui comporte 6 antennes. Que penses tu du besoin ? Merci par avance !
