### ISSUE TITLE
[EPIC] ETQ entreprise je me mélange entre les parcours

### ISSUE THREAD

**Issue by 3lodi3** [gip-inclusion/immersion-facile#1208]
### :thinking: Contexte et problématique (et par qui est-ce remonté ?)

Confusion entre les parcours :
- piloter mon entreprise
- référencer ou modifier mon entreprise

### :tada: Proposition de solution

1 : accès direct à mon espace (page connexion/création de compte IC)
- [x] Ajouter le bouton "Mon espace" en header 
- [x] Déplacer le btn de connexion admin
- [x] Remplacer les wording des accès en homepages : Mon espace entreprise / Mon espace prescripteur
-> Voir si les 35% de tickets liés aux liens non reçus baissent

2 : proposer tout de suite après le référencement sans compte de finaliser son inscription avec IC, sur le site et par email (modifier le mail référencement réussi)
https://www.figma.com/proto/rZtRL0ShjGKfdw43nMUPex/Site---UX-design-2nd-trimestre-2024?page-id=1107%3A1948&type=design&node-id=1107-1949&viewport=-991%2C163%2C0.5&t=kkHLpUVbgdFjeG0n-1&scaling=scale-down&starting-point-node-id=1134%3A281&show-proto-sidebar=1&mode=design

-> Voir si les tickets liés à l'incompréhension du parcours référencement/espace perso entreprise baissent

3 : 
Lancer des A/B tests en revoyant les landing, la navigation ppale et les liens d'accès directs
https://www.figma.com/proto/rZtRL0ShjGKfdw43nMUPex/Site---UX-design-2nd-trimestre-2024?page-id=269%3A327&type=design&node-id=3002-1072&viewport=527%2C593%2C0.16&t=vsdjJGDzKz91hHAP-1&scaling=contain&mode=design

Démo jeudi 4 avril : 
- revoir wording des landing
- creation de compte pour les entreprises / prescripteur différenciée de la convention/de pot offre
- creation des alertes pour les candidats

**Comment by 3lodi3** [comment]
Message :
je souhaite m'enregistrer en temps qu'entreprise accueillante pour une personne qui est censée venir faire son stage en mars, mais je ne peux jamais valider la demande... Tout est bloqué, on me dit qu'il manque des codes, mais quand je reviens au début du formulaire et que je reprend tout a Zéro, il n'y aucun code de demandé! Cela me décourage grandement car j'ai déja perdu beaucoup d'heures pour m'immatriculer sur votre "plateforme". Est il possible d'etre contactée par telephone svp ?

emeline.froment01@gmail.com

**Comment by 3lodi3** [comment]
https://miro.com/app/board/uXjVNvV71ak=/?share_link_id=429269115024

**Comment by 3lodi3** [comment]
- [ ] Rapatrier le référencement entreprise dans le tdb entreprise : le représentant légal Inclusion Connecté a le droit de modifier l'entreprise
- [ ] Ajouter le bouton Se connecter / s'inscrire en header + remplir une convention en mode invité
- [ ] Ajouter en h1 le nom de l'entreprise / le nom du prescripteur (voir en ui si on reprend le système de couleur ou un visuel)
- [ ] Ajouter un select qui permet de basculer entre des tdb entreprise et prescripteur

**Comment by 3lodi3** [comment]
clemence.cantan@exco.fr (entreprise pour tester la modification d'entreprise)

**Comment by 3lodi3** [comment]
Version pré- 4 avril
**Tâches :**
- [ ] Rapatrier le référencement entreprise dans le tdb entreprise : le représentant légal Inclusion Connecté a le droit de modifier l'entreprise
- [ ] Garder tous les onglets affichés pour les entreprises, inscites ou pas dans l'annuaire, avec un renvoi à l'inscription dans l'annuaire pour celles qui ont seulement un compte IC.
- [ ] "Piloter mon entreprise" devient partout "Se connecter/S'inscrire"
- [ ] "Remplir la demande de convention" devient partout "Remplir une convention sans compte"
- [ ] Ajouter le bouton Se connecter / s'inscrire en header + remplir une convention en mode invité
- [ ] Déplacer les Paramètres d'affichage en footer
- [ ] Ajouter en h1 le nom de l'entreprise / le nom du prescripteur (voir en ui si on reprend le système de couleur ou un visuel)
- [ ] Ajouter un select qui permet de basculer entre des tdb entreprise et prescripteur
- [ ] "Référencer ou modifier mon entreprise" devient partout "Référencer ou modifier mon entreprise sans compte" sauf en header (voir la V2 - à discuter, cela implique de demander le SIRET en 1er dans le form de référencement).

### 📷  Prototype

Les différents rôles à préciser (user, admin...) afin de voir si les h1/chapos sont cohérents

Proto : https://www.figma.com/proto/6msAgGCn4id2P3OjI4NRxP/Site---UX-design-1er-semestre-2024?page-id=450%3A229&type=design&node-id=455-38779&viewport=1012%2C3199%2C0.09&t=jGhcxoJRYk611wNp-1&scaling=min-zoom&starting-point-node-id=455%3A38779&show-proto-sidebar=1&mode=design

Fichier pour dev : https://www.figma.com/file/6msAgGCn4id2P3OjI4NRxP/Site---UX-design-1er-semestre-2024?type=design&node-id=450%3A229&mode=dev&t=2Vsy4JIeTdfKA262-1

**Comment by chaibax** [comment]
- faire un funnel de connexion a l'espece pour mesuer les effets des améliorations
