### ISSUE TITLE
EPIC gestion des liens agences - agents

### ISSUE THREAD

**Issue by 3lodi3** [gip-inclusion/immersion-facile#1246]
- [ ] Possibilité de supprimer des liens agence -agents dans l'interface d'admin
- [ ] Possibilité de réaffecter un agent à une autre agence
- [ ] Possibilité de détecter les agences en doublon
- [ ] Gestion des rôles -> ajouter un rôle admin d'agence pour soulager la charge de travail côté Nath

**Comment by 3lodi3** [comment]
On le laisse au frigo car on va donner des droits d'admin aux prescripteurs
