### ISSUE TITLE
ETQ Bizdev météo offre / demandes

### ISSUE THREAD

**Issue by Jessicaceleste1** [gip-inclusion/immersion-facile#1449]
### :thinking: Contexte et problématique (et par qui est-ce remonté ?)

Avoir une météo secteur d activité / offre demande national et régionale.
En effet nous avons de plus en plus de demande à destination d entreprise savoir si on répond ok pour webin et comment orienter sur quel métier.
Effectivement cassé https://metabase.immersion-facile.beta.gouv.fr/dashboard/21-meteo
et en comparaison il faudrait top recherche

### :tada: Proposition de solution
Réparer et ajouter la comparaison offre et demande soit le top recherche

**Comment by bbohec** [comment]
Backlog FAST > https://trello.com/c/c8fvCHGE/7-%C3%A0-prioriser-metabase-equilibrage-offre-et-demande-m%C3%A9t%C3%A9o

**Comment by nathalie-reyre** [comment]
cf travail fait par Pierre https://docs.google.com/presentation/d/1g9HDSVOpNE6DfqjGpBNbPekUbNLRdws8ut7OAcQMsLA/edit?usp=sharing

**Comment by Master-Touks** [comment]
Découper la granularité de temps en mois par mois (idée : tous les mois ou tous les 6 mois).

**Comment by Master-Touks** [comment]
Point avec Chaïb : En partant des recherches qui remontent 0 résultats, est-il possible de relier les recherches par localisation, heure de la recherche et code ROME pour définir si c'est la recherche d'une personne. Au delà de ça, l'idée finale serait d'avoir une liste de métier de CODE ROME en tension sur un territoire sur une période donnée. 

- [ ] Joindre les recherches au code rome 
- [ ] joindre le résultat précédent aux localisations
- [ ] grouper / compter le nombre de recherche à 0 sur un un code rome donnée

**Comment by Jessicaceleste1** [comment]
++++ effectivement la région ARA en fait un enjeu politique avec la prefette. Pour augmenter le nombre d'entreprises accueillantes, ils souhaitent connaitre le top recherche et comparer aux resultats pour faire actionner les entreprises et équilibre l'offre et la demande

**Comment by Jessicaceleste1** [comment]
Top secteurs non couverts en recherche
Terrains de recherche
Recherche terrain d'immersion par région
**top_recherches_par_géo_last_month
top recherches : ça part région ça serait topissime, ensuite ils peuvent voir les entreprises enregistrées**

**Comment by chaibax** [comment]
Next step @Master-Touks 
- Liste par départements des métiers en tensions
- tableau des metiers sans candidats (l'inverse)

**Comment by bbohec** [comment]
J'ai l'impression que cette carte c'est une EPIC et que ce qui a été fait correspond à 
- https://trello.com/c/9VqfKcmz/22-liste-des-metier-en-tensions-sur-if-trop-de-candidat-pas-doffre

Ce qui reste à faire correspond à : 
- #1664   -> https://trello.com/c/6jFG41M4/24-liste-des-metiers-sans-candidatures-trop-doffre-pas-de-mise-en-relation

**Comment by Jessicaceleste1** [comment]
dans le board : https://metabase.immersion-facile.beta.gouv.fr/question/1631-recherche-sans-resultat les résultats qui s'affichent proviennent d'une recherche par région, cependant, ce type de recherche depuis notre moteur ne fonctionne pas.
Il faudrait que la donnée "région" provienne de toutes les villes de la région

**Comment by Master-Touks** [comment]
Migration pour améliorer les performances des requêtes : https://github.com/gip-inclusion/immersion-facile/pull/1789

**Comment by Jessicaceleste1** [comment]
Point fast : recherche national, régional, départemental avec une extraction figée tous les mois, pas besoin que la requête soit en temps réelle

**Comment by Master-Touks** [comment]
Aller regarder s’il y a des offres sans mise en relation, sans convention validée.
