### ISSUE TITLE
ETQ Stage de seconde (1j1s) je veux tracker les recherches faites par les jeunes

### ISSUE THREAD

**Issue by Master-Touks** [gip-inclusion/immersion-facile#1860]
pourriez-vous nous transmettre les éléments suivants :

(aller vérifier l'API de stage de troisième) 

- [ ] Le nombre de mises en contact entre élèves et entreprises 
- [ ] Le nombre d'élèves différents et le nombre de mises en relation correspondantes.
- [ ] Le nombre d'entreprises différentes contactées, avec un classement par secteur, et si possible par zone géographique

Serait-il possible de sonder ces entreprises pour savoir combien de stages ont réellement été réalisés ? Si vous le souhaitez, nous pouvons réaliser ce sondage, si vous nous fournissez les emails. On a qqpart isolées les recherches faites depuis l'API consommée par eux ?

**Comment by Master-Touks** [comment]
Standby
