### ISSUE TITLE
Déclarer un abandon d'immersion

### ISSUE THREAD

**Issue by cecile-dimarco** [gip-inclusion/immersion-facile#730]
### Besoin
Besoin des prescripteurs de faire un décompte exact des heures à déclarer à l'urssaf + d'avoir connaissance la situation des personnes qu'ils suivent (notamment les plus éloignés de l'emploi) pour leur permettre de rebondir rapidement si l'immersion a été source de difficultés.  permettre donc à l'entreprise de passer la convention en statut "interruption"( ou "cessée") sans attendre le mail de bilan. Rendre cette possibilité accessible aussi au prescripteur s'il a l'info. Permettre de saisir la date de fin afin de recalculer le nombre d'heures réelles effectuées.

### Proposition

- [ ] L'entreprise peut déclarer un abandon depuis le mail de validation de convention : #3129 

- [ ] Le prescripteur peut déclarer un abandon depuis la page de pilotage d'une convention : #3048 

- [ ] Une fois le bilan rempli, il faut annuler la programmation de l'envoi des notifications de bilan à remplir la veille de fin d'immersion : #3130 

### 📷 Maquettes

**Bouton "Déclarer un abandon"** 
Bouton disponible depuis la convention pour les prescripteurs.
https://github.com/user-attachments/assets/441e097b-799e-4dcc-9faf-05bf203d7b29

[Lien Figma
](https://www.figma.com/design/3LyqYKxeOuj2LuZSvf5TAW/Parcours-emails?node-id=0-1&node-type=canvas&t=Lh8Q7wHpzFGF3Eyw-0)

**Email : Entreprise - Abandon de l’immersion** 
Objet : Immersion Facilitée - Finalisation de l’immersion de [Nom du candidat] 
Date d’envoi : Après la déclaration d’un abandon de l’immersion en cours
![Image](https://github.com/user-attachments/assets/0025f3d8-9b73-4d95-bc01-81a3c3802b9f)

**Email : Prescripteur - Abandon de l’immersion** 
Objet : Immersion Facilitée - Abandon de l’immersion de [Nom du candidat] 
Date d’envoi : Après la déclaration d’un abandon de l’immersion en cours
![Image](https://github.com/user-attachments/assets/7411c0f2-abc1-4fe5-bfb3-2bb06aaf0608)

**Comment by cecile-dimarco** [comment]
Permettre à l'entreprise et au candidat de voir immédiatement que lors demande d'interruption de l'immersion a bien été prise en compte et ne pas attendre le mail de fin d'immersion

**Comment by cecile-dimarco** [comment]
https://miro.com/app/board/uXjVK3FaGlE=/

**Comment by nathalie-reyre** [comment]
8 % des immersions pour lesquelles l'entreprise a commenté le mail de bilan sont déclatées abandonnées avant leur fin. Soit, si on raisonne par mois, cela permettrait de  mettre à jour environ 1520 immersions/mois

**Comment by nathalie-reyre** [comment]
Cycle de vie de l'immersion --> statut abandonné qui signifie que l'immersion n'est pas allée à son terme (et que la convention n'a pas été respectée totalement)
L'entreprise ou le prescripteur  vont sur la page de la convention validée --> voit un bouton "déclarer un abandon' clique sur le bouton "abandonné" --> ouvre un champ de date d'abandon (attention préciser qu'on demande le dernier jour de présence) et un champ commentaire (si le commentaire est fait par le prescripteur, le rendre visible). Annulation de l'envoi du mail de bilan.

Attention à l'API convention -  on ne peut pas faire remonter ce statut abandonné dans l'APi à l'heure actuelle.

**Comment by cecile-dimarco** [comment]
Pour info, si besoin d'interview 
![Image](https://github.com/user-attachments/assets/af214fde-cc14-4885-943c-fd31ec579b1d)
achazot@mljeuneloire.org

**Comment by mdamourette** [comment]
Dans ce ticket, on prend en compte le fait de pouvoir interrompre une immersion avant son terme.

La saisie des horaires exacts (coupure pendant l'immersion) sera fait dans un second temps, après avoir fait de la recherche sur le sujet.

**Comment by nathalie-reyre** [comment]
la saisie des horaires est réglée. Pourrait on prévoir une fonctionnalité via le tableau de bord pour permettre à un tuteur de déclarer un abandon et ce faisant déclencher l'envoi du bilan ?

**Comment by mdamourette** [comment]
C'est déjà prévu dans les maquettes. Je ne sais pas pourquoi le ticket est dans "Prêt à clarifier", je le déplace dans "À démo à l'équipe".
