### ISSUE TITLE
ETQ que structure, le siret que je saisis quand j'inscris mon agence est vérifié à la soumission du formulaire

### ISSUE THREAD

**Issue by nathalie-reyre** [gip-inclusion/immersion-facile#732]
### :thinking: Contexte et problématique

Aujourd'hui tous les prescripteurs quoi se référencent doivent indiquer leur siret mais nous ne le soumettons pas à la même vérification que le siret des entreprises.  Cette donnée nous est demandée par Wordline pour pouvoir faire tourner l'API convention et implémenter les conventions dans I Milo.
Nous pouvons intégrer cette donnée dans notre API convention mais nous avons besoin de vérifier que le siret est saisi sans erreur.
Aujourd'hui, nous avons 386 prescripteurs référencés sur IF sans siret dont 66 missions locales. **325 sont actives**
Nous avons également 121 agences PE sans siret mais avec code azur. **Seulement 43 sont actives**. 

### :tada: Proposition de solution

 
Modifier l'emplacement du la saisie du SIRET pour que ce soit le premier champs du formulaire de référencement des structures.
Lancer la vérification : je pense que les emplois de l'inclusion ou Data inclusion doivent avoir tous les siret des missions locales et de plein d'autres structures d'insertion qui sont des prescripteurs potentiels. Je me dis que la vérif du siret quand une structure s'inscrit chez nous pourrait se faire en appelant d'abord l'API SIRET de data inclusion (si elle existe) puis en back up l'annuaire des entreprises. 
Permettre la saisie d'un même siret pour plusieurs agences car c'est déjà souvent le cas.
Permet de pré-remplir les champs nom et adresse
je pense que les emplois de l'inclusion ou Data inclusion doivent avoir tous les siret des missions locales et de plein d'autres structures d'insertion qui sont des prescripteurs potentiels. Je me dis que la vérif du siret quand une structure s'inscrit chez nous pourrait se faire en appelant d'abord l'API SIRET de data inclusion (si elle existe) puis en back up l'annuaire des entreprises. 
Permettre la saisie d'un même siret pour plusieurs agences car c'est déjà souvent le cas.
Permettre de modifier le nom (même comportement que le nom d'enseigne du formulaire entreprise) afin de pouvoir personnaliser le nom des agences comme aujourd'hui.
Permettre de modifier l'adresse de l'agence  car elle sera parfois différente de celle liée au SIRET (notamment quand on a plusieurs agences rattachées au même siret).

Reprise de stock : script pour trouver automatiquement les siret manquants à partir des données de data inclusion ???? Quelles données pourraient permettre d'identifier les structures ? 
Supprimer définitivement les structures rejetées ou fermées afin de ne pas faire être obligées de chercher les siret pour ces dernières. Quid des conventions qui pourraient y être attachées ? ou mettre par défaut un siret générique pour tous ces établissements fermés (siret ministère du travail par ex)
PE --> faire une mise à jour avec l'API PE ? Quid des agences avec conventions attachées qui ont été fermées depuis 2 ans ?

**Comment by 3lodi3** [comment]
- [ ] Vérifier la validité du SIRET à la soumission du formulaire de création d'agence en backend - et refuser la création si le SIRET n'est pas valide ou que l'entreprise est inactive.
- [ ] Vérifier la validité du SIRET à la soumission du formulaire de création d'agence en frontend.
- [ ] Pour éviter les doublons : vérifier type + adresse + active : si les deux sont identiques, on refuse la création du doublon et on donne le nom de l'agence à l'utilisateur. On vérifie à l'ajout ou à la modif.
- [ ] Dashboard metabase pour Nathalie pour traiter les ajouts d'agences.
- [ ] Partir d'une base ou API MILO recensant les structures (dans data inclusion ou UMML ou wordline) pour faire un mapping des structures.
- [ ] Mettre à jour les agences PE pour anticiper Inclusion Connect avec agence.
