### ISSUE TITLE
[EPIC] ETQ entreprise, j'ai accès à mon tableau de bord

### ISSUE THREAD

**Issue by nathalie-reyre** [gip-inclusion/immersion-facile#753]
### :thinking: Contexte et problématique

les entreprises ne reçoivent pas ou ne retrouvent dans leurs mails les notifications d'Immersion Facilitée. 
Le support est submergé de demandes pour renvoyer les notifications pour signer les demandes ou recevoir les conventions.
Les candidats qui contactent les entreprises ne reçoivent pas de réponse

### :tada: Proposition de solution

 proposer aux entreprises d'accéder à leur propre BO pour gérer les demandes de convention,  voir les mises en relation, y répondre, mettre à jour les informations de leur entreprise.
Le tableau de bord pourra être évolutif, le plus urgent étant l'accès aux demandes de convention

**Comment by 3lodi3** [comment]
Réunion avec Sonia, Benjamin et Nathalie : https://www.notion.so/gip-inclusion/TdB-entreprises-c345217f7fff4d0d97ae565daf5d01e2?pvs=4

**Comment by 3lodi3** [comment]
Chemin pour arriver à IC entreprises (lien rapide en header DSFR) : https://www.figma.com/proto/s43XSEkyYPaeGs2sxp62iq/Site---UX-design-2nd-semestre-2023?page-id=2269%3A16967&type=design&node-id=2274-17026&viewport=-1226%2C-795%2C0.66&t=peVJ1shLOms5iQRD-8&scaling=min-zoom&starting-point-node-id=2274%3A17026&hide-ui=1

**Comment by JeromeBu** [comment]
- [ ] Se connecter avec inclusion connect et faire le lien avec le siret concerné
- [ ] Si la personne inclusion connecté a le même mail que celui de l'établissement référencé alors il est considéré admin de cette établissements, c'est à dire qu'il a les droits de modifications sur cette entreprise.
- [ ] un utilisateur inclusion connecté dont le email match un acteur de type "establishment-representative", doit avoir accès à la convention concerné.
- [ ] Gérer différent droit par utilisateur et par siret (actuellement ont sait qu'il y a l'admin de l'établissement)

**Comment by JeromeBu** [comment]
TODO Gromming

**Comment by 3lodi3** [comment]
MVP : lorsqu'on remplit une demande de convention on propose à l'entreprise de créer un compte IC pour suivre ses conventions  -> l'email du signataire de la convention qui a un rôle "signataire"
- Accès au tableau de suivi de ses conventions : seul le signataire des conventions peut piloter ses propres conventions
- A côté de ça on aura un admin (référent de l'entreprise accueillante) 

On aura potentiellement 3 rôles :
- Admin : peut gérer toutes infos liées à l'entreprise, les utilisateurs de différents rôles liés à l'entreprise
- Signataire : peut piloter ses conventions
- Viewer : peut juste consulter ses conventions (structures d'accompagnement, tuteurs non signataires...)

**Comment by JeromeBu** [comment]
Etapes dans d'autre issues :

- [ ] #790
