### ISSUE TITLE
ETQ équipe IF, je voudrais pouvoir catégoriser automatiquement les tickets arrivant au support afin de pouvoir tracker finement l'impact des nouvelles features  

### ISSUE THREAD

**Issue by 3lodi3** [gip-inclusion/immersion-facile#798]
### :thinking: Contexte et problématique (et par qui est-ce remonté ?)

Nous avons besoin de tracker finement les types de tickets arrivant au support pour voir lesquels baissent / augmentent / stagnent. Cela nous aidera à prioriser les features et à mesurer leur impact.

- Tickets liés au parcours de signature
- Tickets liés à des demandes de modifs
- Tickets liés aux mer
- Autres

### :tada: Proposition de solution

https://help.crisp.chat/en/article/what-is-a-segment-and-how-can-it-help-your-team-88hhzw/

**Comment by 3lodi3** [comment]
En gros on voudrait automatiser ce fichier manuel : https://docs.google.com/spreadsheets/d/1oGRLEZQIK1IVkBAZ9UqH58JD-AaROtcDHnjw7vC60Mg/edit#gid=0

Atelier à prévoir avec Pierre et un dev

**Comment by 3lodi3** [comment]
- [ ] tracker le nombre de tickets global / mois 
- [ ] tracker le temps de résolution des tickets moyen au global / mois 
- [ ] tracker le nombre de tickets par segment / mois
- [ ] tracker le temps de résolution moyen par ticket / segment / mois
- [ ] tracker le ratio nombre de conventions validées / nombre de tickets par mois
- [ ] tracker nombre de mises en relations / nombre de tickets par mois

**Comment by Master-Touks** [comment]
Hypothèse soulevé avec Pierre : 
- Récupérer tous les tickets 
- Calculer la différence de temps entre la date d'ouverture du ticket et la date de fermeture du ticket
- Regrouper les temps par segments pour comprendre quel segments demande du temps 
- visualiser ?
